name: Weekly SEO Task

on:
  schedule:
    - cron: "0 1 * * 1" # 11am AEST (00:00 UTC +11h = 1am UTC Monday)
  workflow_dispatch:

jobs:
  run-seo-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install

      - name: Run Script
        env:
          SERP_API_KEY: ${{ secrets.SERP_API_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          SEED_KEYWORD: ${{ secrets.SEED_KEYWORD }}
        run: node index.js
