name: Weekly SEO Task

on:
  schedule:
    - cron: "0 1 * * 1" # 11am AEST (00:00 UTC +11h = 1am UTC Monday)
  workflow_dispatch:

jobs:
  run-seo-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install

      - name: Run Script
        env:
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          SERP_API_KEY: ${{ secrets.SERP_API_KEY }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SEED_KEYWORD: ${{ vars.SEED_KEYWORD }}
          EMAIL_USER: ${{ vars.EMAIL_USER }}
          EMAIL_FROM: ${{ vars.EMAIL_FROM }}
          EMAIL_TO: ${{ vars.EMAIL_TO }}
        run: node index.js
